config/routes.rb
Rails.application.routes.draw do
  resources :my_annotations do
    collection do
      get 'list_anno'
    end
  end

  resources :explore do
    collection do
      get 'random'
      get 'gallery'
      get 'list_anno'
    end
  end

  resources :image_annotations do
    collection do
      get 'testit'
    end
  end

  resources :images

  resources :image2_tests

  resources :image_tests do
    collection do
      get 'testit'
    end
  end

  devise_for :users
  resources :users

  root 'explore#index'

end

app/models/image_annotation.rb
class ImageAnnotation < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
end

app/controllers/image_annotations_controller.rb
class ImageAnnotationsController < ApplicationController
  before_action :set_image_annotation, only: [:show, :edit, :update, :destroy]

  # GET /image_annotations
  # GET /image_annotations.json
  def index
    @image_annotations = ImageAnnotation.all
  end

  # GET /image_annotations/1
  # GET /image_annotations/1.json
  def show
  end

  # GET /image_annotations/new
  def new
    @image_annotation = ImageAnnotation.new
  end

  # GET /image_annotations/1/edit
  def edit
  end

  # POST /image_annotations
  # POST /image_annotations.json
  def create
    @image_annotation = ImageAnnotation.new(process_params)

    respond_to do |format|
      if @image_annotation.save
        format.html { redirect_to @image_annotation, notice: 'Image annotation was successfully created.' }
        format.json { render :show, status: :created, location: @image_annotation }
      else
        format.html { render :new }
        format.json { render json: @image_annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_annotations/1
  # PATCH/PUT /image_annotations/1.json
  def update
    respond_to do |format|
      if @image_annotation.update(image_annotation_params)
        format.html { redirect_to @image_annotation, notice: 'Image annotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_annotation }
      else
        format.html { render :edit }
        format.json { render json: @image_annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_annotations/1
  # DELETE /image_annotations/1.json
  def destroy
    @image_annotation.destroy
    respond_to do |format|
      format.html { redirect_to image_annotations_url, notice: 'Image annotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def testit
    images = []
    annotations = Image.find(params['image_id']).image_annotations
    annotations.each do |anno|
      images << {src: anno.src,
                 text: anno.text,
                 shapes: JSON.parse(anno.shapes)}
    end
    puts annotations.to_json
    puts images.to_json
    render json: images
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_annotation
      @image_annotation = ImageAnnotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_annotation_params
      params.require(:image_annotation).permit(:src, :shapes, :user_id)
    end

    def process_params
      shapes = params[:shapes].to_json

      annotation = {:src => params[:src],
                    :shapes => shapes,
                    :text => params[:text]}

      annotation[:image_id] = Image.where(:url => params[:src]).first.id

      if current_user
        annotation[:user_id] = current_user.id
      end      
      return annotation
    end
end

app/views/image_annotations/_form.html.erb
<%= form_for(@image_annotation) do |f| %>
  <% if @image_annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_annotation.errors.count, "error") %> prohibited this image_annotation from being saved:</h2>

      <ul>
      <% @image_annotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_src %><br>
    <%= f.text_field :image_src %>
  </div>
  <div class="field">
    <%= f.label :shapes %><br>
    <%= f.text_field :shapes %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_annotations/edit.html.erb
<h1>Editing image_annotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_annotation %> |
<%= link_to 'Back', image_annotations_path %>

app/views/image_annotations/index.html.erb
<h1>Listing image_annotations</h1>

<table>
  <thead>
    <tr>
      <th>Image src</th>
      <th>Shapes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_annotations.each do |image_annotation| %>
      <tr>
        <td><%= image_annotation.image_src %></td>
        <td><%= image_annotation.shapes %></td>
        <td><%= image_annotation.user %></td>
        <td><%= link_to 'Show', image_annotation %></td>
        <td><%= link_to 'Edit', edit_image_annotation_path(image_annotation) %></td>
        <td><%= link_to 'Destroy', image_annotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image annotation', new_image_annotation_path %>

app/views/image_annotations/new.html.erb
<h1>New image_annotation</h1>

<%= render 'form' %>

<%= link_to 'Back', image_annotations_path %>

app/views/image_annotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image src:</strong>
  <%= @image_annotation.image_src %>
</p>

<p>
  <strong>Shapes:</strong>
  <%= @image_annotation.shapes %>
</p>

<p>
  <strong>User:</strong>
  <%= @image_annotation.user %>
</p>

<%= link_to 'Edit', edit_image_annotation_path(@image_annotation) %> |
<%= link_to 'Back', image_annotations_path %>