config/routes.rb
Rails.application.routes.draw do
  resources :my_annotations do
    collection do
      get 'list_anno'
    end
  end

  resources :explore do
    collection do
      get 'random'
      get 'gallery'
      get 'list_anno'
    end
  end

  resources :image_annotations do
    collection do
      get 'testit'
    end
  end

  resources :images

  resources :image2_tests

  resources :image_tests do
    collection do
      get 'testit'
    end
  end

  devise_for :users
  resources :users

  root 'explore#index'

end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  before_filter :notify_new_achievements
  def index
    # Get what's new
    @new_images = Image.limit(10).order('id desc')

    # Get random
    @random_images = []
    (1..10).each do |i|
      @random_images << Image.offset(rand(Image.count)).first
    end

    @hot_images = Image.top10;

    @new_annotated_images = ImageAnnotation.limit(10).order('created_at DESC').map{|a| a.image}.uniq

    render layout: 'exploreindex'
  end

  def show
    @image = Image.find(params[:id])
  end

  def random
    @random_image =  Image.offset(rand(Image.count)).first
  end

  def gallery
    @images = Image.paginate(page: params[:page], per_page: 15).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def list_anno
    annos = []
    image_annotations = ImageAnnotation.where(:image_id => params['image_id']).all 
    image_annotations.each do |anno|
      annos << {src: anno.src,
                editable: false,
                text: anno.text,
                shapes: JSON.parse(anno.shapes)}
    end
    render json: annos
  end
end

app/views/explore/_carousel_image.html.erb
<div class="item <%= image_counter == 0? "active":""%>">
  <%= link_to url_for(controller: :explore, id: image.id, action: :show) do %>
  <%= image_tag image.url %> 
  <% end %>
  <div class="carousel-caption">
  	<h5><%= File.basename(image.url, '.jpg') %></h5>
    <p>sol <%= image.sol %> | <%= image.image_time %></p>
  </div>
</div>

app/views/explore/_carousel_indicator.html.erb
<li data-target="#carousel-example-generic" data-slide-to="<%= image_counter %>" <%= "class=\"active\"" if image_counter == 0 %>></li>

app/views/explore/_image.html.erb
<%= link_to url_for(controller: :explore, id: image.id, action: :show) do %>
<%= image_tag image.url, width: "300" %> 
<% end %>

app/views/explore/gallery.html.erb
<div class="page-header">
  <h3>Mars Images</h3>
</div>
 
<div id="my-images">
  <%= render partial: "image", collection: @images %>
</div>
 
<div id="infinite-scrolling">
  <%= will_paginate @images %>
</div>

app/views/explore/gallery.js.erb
$('#my-images').append('<%= j render partial: "image", collection: @images %>');
<% if @images.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @images %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/explore/index.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" style="background-image: url(assets/mars3.jpg); background-size: 100%;">
      <div class="container">
        <h2>Hello Mars Explorers</h2>
        <p>The Mars rovers Curiosity and Opportunity have been on the move capturing fantastic photos of the Red planet for years. Help us analyze these images by annotating them. Share your scientific findings and become Mars Scitizens!</p>
        <p><%= link_to "<button type='button' class='btn btn-primary btn-lg'><span class='glyphicon glyphicon-search'></span> Start Exploring</button>".html_safe, random_explore_index_path %></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-6">
          <h2>What's Hot</h2>
          <div id="carousel-whats-hot" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <%= render partial: 'carousel_indicator', collection: @hot_images, as: :image  %>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <%= render partial: 'carousel_image', collection: @hot_images, as: :image  %>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-whats-hot" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-whats-hot" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>

        <div class="col-md-6">
          <h2>Random Images</h2>
          <div id="carousel-random-images" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <%= render partial: 'carousel_indicator', collection: @random_images, as: :image  %>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <%= render partial: 'carousel_image', collection: @random_images, as: :image  %>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-random-images" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-random-images" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <h2>New Images</h2>
          <div id="carousel-whats-new" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <%= render partial: 'carousel_indicator', collection: @new_images, as: :image  %>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <%= render partial: 'carousel_image', collection: @new_images, as: :image  %>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-whats-new" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-whats-new" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>

        <div class="col-md-6">
          <h2>New Annotations</h2>
          <div id="carousel-new-annos" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <%= render partial: 'carousel_indicator', collection: @new_annotated_images, as: :image  %>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <%= render partial: 'carousel_image', collection: @new_annotated_images, as: :image  %>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-new-annos" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-new-annos" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>      
      </div>

      
    </div>

app/views/explore/random.html.erb
<script>
jQuery(document).ready(function($) {

anno.makeAnnotatable(document.getElementById('something'));
anno.addHandler('onAnnotationCreated', function(annotation) {
    console.log(annotation.text);
    console.log(annotation.shapes[0].geometry.x);
    $.post( '/image_annotations.json', annotation );
});

$.getJSON( "/my_annotations/list_anno?image_id=<%= @random_image.id %>", function( data ) {
  $.each( data, function( key, val ) {
    anno.addAnnotation(val);
  });
});

});
</script>

<%- model_class = ImageTest -%>
<div class="page-header">
  <h3>Exploring random images</h3>
</div>

<div class="col-md-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Instruction</h3>
    </div>
    <div class="panel-body">
      Click and drag on image to annotate interesting features.
      <% unless current_user %>
      <br/><br/><%= link_to 'Register', new_user_registration_path %> and <%= link_to 'sign in', new_user_session_path %> to keep track of your works and to earn achievements.
      <% end %>      
    </div>
  </div>    
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Image Info</h3>
    </div>
    <div class="panel-body">
      <strong><%= model_class.human_attribute_name(:sol) %>:</strong> <%= @random_image.sol %><br/>
      <strong><%= model_class.human_attribute_name(:camera_type) %>:</strong> <%= @random_image.camera_type %><br/>
      <strong><%= model_class.human_attribute_name(:image_time) %>:</strong> <%= @random_image.image_time %><br/>
      <strong># of Annotations:</strong> <%= @random_image.image_annotations.count %>
      <%= "(Be the first one to annotate this picture)" if @random_image.image_annotations.count == 0 %>
    </div>
  </div>
  <div class="text-center"><%= link_to "<button type='button' class='btn btn-primary btn-sm'><span class='glyphicon glyphicon-question-sign'></span> Random Image</button>".html_safe, random_explore_index_path %></div><br/>
  <div class="text-center"><%= link_to "<button type='button' class='btn btn-primary btn-sm'><span class='glyphicon glyphicon-picture'></span> Image Gallery</button>".html_safe, gallery_explore_index_path %></div>
</div>
<div class="col-md-10">
  <div>
    <%= image_tag @random_image.url, :id => 'something' %>
  </div>
</div>

app/views/explore/show.html.erb
<script>
jQuery(document).ready(function($) {

anno.makeAnnotatable(document.getElementById('something'));
anno.addHandler('onAnnotationCreated', function(annotation) {
    console.log(annotation.text);
    console.log(annotation.shapes[0].geometry.x);
    $.post( '/image_annotations.json', annotation );
});

$.getJSON( "/explore/list_anno?image_id=<%= @image.id %>", function( data ) {
  $.each( data, function( key, val ) {
    anno.addAnnotation(val);
  });
});

});
</script>

<%- model_class = ImageTest -%>
<div class="page-header">
  <h3>Exploring Mars</h3>
</div>

<div class="col-md-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Instruction</h3>
    </div>
    <div class="panel-body">
      Click and drag on image to annotate interesting features.
      <% unless current_user %>
      <br/><br/><%= link_to 'Register', new_user_registration_path %> and <%= link_to 'sign in', new_user_session_path %> to keep track of your works and to earn achievements.
      <% end %>
    </div>
  </div>  
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Image Info</h3>
    </div>
    <div class="panel-body">
      <strong><%= model_class.human_attribute_name(:sol) %>:</strong> <%= @image.sol %><br/>
      <strong><%= model_class.human_attribute_name(:camera_type) %>:</strong> <%= @image.camera_type %><br/>
      <strong><%= model_class.human_attribute_name(:image_time) %>:</strong> <%= @image.image_time %><br/>
      <strong># of Annotations:</strong> <%= @image.image_annotations.count %>
      <%= "(Be the first one to annotate this picture)" if @image.image_annotations.count == 0 %>
      <br/>
    </div>
  </div>
  <div class="text-center"><%= link_to "<button type='button' class='btn btn-primary btn-sm'><span class='glyphicon glyphicon-question-sign'></span> Random Image</button>".html_safe, random_explore_index_path %></div><br/>
  <div class="text-center"><%= link_to "<button type='button' class='btn btn-primary btn-sm'><span class='glyphicon glyphicon-picture'></span> Image Gallery</button>".html_safe, gallery_explore_index_path %></div>  
</div>
<div class="col-md-10">
  <div>
    <%= image_tag @image.url, :id => 'something' %>
  </div>
</div>